name: Build and publish client and server Docker images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push client image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/client/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/t4fids-client:latest

    - name: Build and push server image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/server/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/t4fids-server:latest