name: Build and publish client and server Docker images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      OWNER_LOWER: ${{ github.repository_owner }}

    steps:
    - name: Set lowercase owner
      id: owner-lower
      run: echo "owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push client image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/client/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.owner-lower.outputs.owner_lower }}/t4fids-client:latest

    - name: Build and push server image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/server/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.owner-lower.outputs.owner_lower }}/t4fids-server:latest